baseurl: "/"
languageCode: "en-us"
title: "Rivet"
paginate: 10
enableEmoji: true
taxonomies:
  category: categories
  addOnTag: addOnTags
  tag: tags
outputs:
  section: ["html"]
params:
  rivetVersion: 1.3.0
  tagline: "Design System"
  googleAnalytics: "UA-100560495-3"
  devGoogleAnalytics: "UA-100560495-4"
  githubRepo: "https://github.com/indiana-university/rivet-source"
  downloadLink: "https://github.com/indiana-university/rivet-source/releases/download/v1.3.0/rivet.zip"
  axureKit: "https://github.iu.edu/UITS/rivet/releases/download/v1.0.0/rivet-axure-1.0.rp"
  description: "Use Rivet to create UITS software that is accessible, usable, and consistent."
  resourceLinks:
    -
      text: "User Experience Office"
      url: "https://uxo.iu.edu"
    -
      text: "Accessibility Evaluations"
      url: "https://a11y.iu.edu/"
    -
      text: "Rivet Software Design System"
      url: "/"
      self: true
    -
      text: "IU Framework for WCMS"
      url: "https://framework.iu.edu/"
  blogSidebar:
    title: Learn about Rivet
    description: "Updates on new features, tutorials, and news about Rivet releases."
refLinksErrorLevel: WARNING